const label = (name: string) => `{{json (index .Labels "com.deploylite.${name}")}}`;
const resource = `"name":{{json .Name}},"driver":{{json .Driver}},"scope":{{json .Scope}},"optionsCount":{{len .Options}},"owner":${label("owner")},"projectId":${label("project")},"resourceKind":${label("resource.kind")},"resourceKey":${label("resource.key")}`;
export const COMPOSE_NETWORK_INSPECT_FORMAT = `{"id":{{json .Id}},"internal":{{json .Internal}},${resource}}`;
export const COMPOSE_VOLUME_INSPECT_FORMAT = `{"createdAt":{{json .CreatedAt}},${resource}}`;
const containerLabel = (name: string) => `{{json (index .Config.Labels "com.deploylite.${name}")}}`;
export const COMPOSE_CONTAINER_INSPECT_FORMAT = `{"id":{{json .Id}},"owner":${containerLabel("owner")},"projectId":${containerLabel("project")},"service":${containerLabel("compose.service")},"composeRevisionId":${containerLabel("compose.revision")},"composeConfigDigest":${containerLabel("compose.config-digest")},"composeEnvironmentDigest":${containerLabel("compose.environment-digest")},"effectiveImage":{{json .Config.Image}},"running":{{json .State.Running}},"networks":[{{$first := true}}{{range $name,$network := .NetworkSettings.Networks}}{{if not $first}},{{end}}{{$first = false}}{"name":{{json $name}},"networkId":{{json $network.NetworkID}}}{{end}}],"mounts":[{{range $i,$mount := .Mounts}}{{if $i}},{{end}}{"type":{{json $mount.Type}},"name":{{json $mount.Name}},"target":{{json $mount.Destination}},"readOnly":{{json (not $mount.RW)}}}{{end}}],"configuredMounts":[{{range $i,$mount := .HostConfig.Mounts}}{{if $i}},{{end}}{"type":{{json $mount.Type}},"name":{{json $mount.Source}},"target":{{json $mount.Target}},"readOnly":{{json $mount.ReadOnly}}}{{end}}]}`;
const replacementLabel = (name: string) => `{{json (index .Config.Labels "com.deploylite.compose.${name}")}}`;
export const COMPOSE_REPLACEMENT_CANDIDATE_INSPECT_FORMAT = `{"id":{{json .Id}},"name":{{json .Name}},"owner":{{json (index .Config.Labels "com.deploylite.owner")}},"projectId":{{json (index .Config.Labels "com.deploylite.project")}},"service":${replacementLabel("service")},"commandId":${replacementLabel("command")},"revisionId":${replacementLabel("revision")},"configDigest":${replacementLabel("config-digest")},"environmentDigest":${replacementLabel("environment-digest")},"image":{{json .Config.Image}},"running":{{json .State.Running}},"networks":[{{$first := true}}{{range $name,$network := .NetworkSettings.Networks}}{{if not $first}},{{end}}{{$first = false}}{{json $name}}{{end}}],"mounts":[{{range $i,$mount := .Mounts}}{{if $i}},{{end}}{"source":{{json $mount.Name}},"target":{{json $mount.Destination}},"readOnly":{{json (not $mount.RW)}}}{{end}}]}`;
export const COMPOSE_REPLACEMENT_HEALTH_FORMAT = `{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}`;
export const COMPOSE_REPLACEMENT_HEALTHCHECK_FORMAT = `{{if .Config.Healthcheck}}{{if .Config.Healthcheck.Test}}{{if gt (len .Config.Healthcheck.Test) 0}}yes{{else}}no{{end}}{{else}}no{{end}}{{else}}no{{end}}|{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}`;
export const COMPOSE_REPLACEMENT_NETWORK_FORMAT = `{"networks":[{{$first := true}}{{range $name,$network := .NetworkSettings.Networks}}{{if not $first}},{{end}}{{$first = false}}{"name":{{json $name}},"aliases":{{json $network.Aliases}}}{{end}}]}`;
export const COMPOSE_INSPECTION_FORMATS: ReadonlySet<string> = new Set([COMPOSE_NETWORK_INSPECT_FORMAT, COMPOSE_VOLUME_INSPECT_FORMAT, COMPOSE_CONTAINER_INSPECT_FORMAT,
  COMPOSE_REPLACEMENT_CANDIDATE_INSPECT_FORMAT, COMPOSE_REPLACEMENT_HEALTH_FORMAT, COMPOSE_REPLACEMENT_HEALTHCHECK_FORMAT, COMPOSE_REPLACEMENT_NETWORK_FORMAT]);
