import { describe, expect, it, vi } from "vitest";
import { DockerCliImageTransport } from "./docker-cli-image-transport.js";
const digest = `sha256:${"a".repeat(64)}`; const candidate = { candidateId: "dep-1:candidate:cmd-1", deploymentId: "dep-1", effectiveImage: `registry.example.com/team/app@${digest}`, runtimePort: 3000 } as const;
describe("DockerCliImageTransport", () => {
  it("delegates lifecycle operations to safe argv and does not orchestrate", async () => { const run = vi.fn(async (argv: readonly string[]) => ({ exitCode: 0, signal: null, stdout: argv[1] === "inspect" ? (argv[3]?.includes("Labels") ? `agent-1|dep-1|dep-1:candidate:cmd-1|${candidate.effectiveImage}` : "healthy") : "", stderr: "" })); const transport = new DockerCliImageTransport({ runner: { run }, owner: "agent-1", hostPort: 43000, containerPort: 3000, allowedNetworks: [] }); const controller = new AbortController(); await transport.startCandidate(candidate, controller.signal); expect(run.mock.calls[0]?.[0]).toContain("--read-only"); expect(run.mock.calls[0]?.[0]).not.toContain("--privileged"); expect(await transport.checkHealth(candidate, controller.signal)).toBe(true); await transport.promoteCandidate(candidate, controller.signal); await transport.discardCandidate(candidate, controller.signal); expect(run).toHaveBeenCalledTimes(6); });
  it("fails closed when ownership labels do not match", async () => { const run = vi.fn(async (argv: readonly string[]) => ({ exitCode: 0, signal: null, stdout: argv[3]?.includes("Labels") ? `other|dep-1|dep-1:candidate:cmd-1|${candidate.effectiveImage}` : "", stderr: "" })); const transport = new DockerCliImageTransport({ runner: { run }, owner: "agent-1", hostPort: 43000, containerPort: 3000, allowedNetworks: [] }); await expect(transport.discardCandidate(candidate, new AbortController().signal)).rejects.toMatchObject({ name: "DockerCliTransportFailure" }); expect(run).toHaveBeenCalledTimes(1); });
  it("reports non-zero exits as typed failures", async () => { const transport = new DockerCliImageTransport({ runner: { run: vi.fn(async () => ({ exitCode: 1, signal: null, stdout: "", stderr: "password=hidden" })) }, owner: "agent-1", hostPort: 43000, containerPort: 3000, allowedNetworks: [] }); await expect(transport.promoteCandidate(candidate, new AbortController().signal)).rejects.toMatchObject({ name: "DockerCliTransportFailure" }); });
  it("invokes the runner for production-shaped deployment identities", async () => { const run = vi.fn(async (argv: readonly string[]) => ({ exitCode: 0, signal: null, stdout: argv[1] === "inspect" ? "healthy" : "", stderr: "" })); const productionCandidate = { ...candidate, deploymentId: "dep_0123456789abcdef", candidateId: "dep_0123456789abcdef:candidate:command_1" }; const transport = new DockerCliImageTransport({ runner: { run }, owner: "agent_1", hostPort: 43000, containerPort: 3000, allowedNetworks: [] }); await transport.startCandidate(productionCandidate, new AbortController().signal); await transport.checkHealth(productionCandidate, new AbortController().signal); expect(run).toHaveBeenCalledTimes(2); expect(run.mock.calls[0]?.[0].some((token) => token.includes("dep_0123456789abcdef"))).toBe(true); });
  it("requires the exact proven restore identity", async () => { const run = vi.fn(async () => ({ exitCode: 0, signal: null, stdout: "agent-1|dep-1|dep-1:candidate:prior|registry.example.com/other@sha256:" + "b".repeat(64), stderr: "" })); const transport = new DockerCliImageTransport({ runner: { run }, owner: "agent-1", hostPort: 43000, containerPort: 3000, allowedNetworks: [] }); const receipt = { deploymentId: "dep-1", candidateId: "dep-1:candidate:prior", effectiveImage: candidate.effectiveImage, runtimePort: 3000, health: "passed" as const, terminalStatus: "succeeded" as const, rollback: { target: null, result: "not-required" as const }, proven: true as const }; await expect(transport.restorePrior(receipt, new AbortController().signal)).rejects.toMatchObject({ name: "DockerCliTransportFailure" }); expect(run).toHaveBeenCalledTimes(1); });
});
