import type { DockerImageCandidateV1, DockerImageTransport, ProvenDockerImageExecutionReceiptV1 } from "@deploylite/domain";
import { buildDockerInspectArgv, buildDockerOwnedStopLookupArgv, buildDockerOwnershipInspectArgv, buildDockerRemoveArgv, buildDockerRenameArgv, buildDockerRestoreInspectArgv, buildDockerRunArgv, buildDockerStartArgv, buildDockerStopArgv, buildDockerStopOwnershipInspectArgv } from "./docker-cli-argv.js";
import type { DockerProcessExit } from "./docker-process-runner.js";

export class DockerCliTransportFailure extends Error { constructor(readonly operation: string, readonly exit?: DockerProcessExit) { super(`docker ${operation} failed`); this.name = "DockerCliTransportFailure"; } }
export class DockerCliTransportCanceled extends Error { constructor(readonly operation: string) { super(`docker ${operation} canceled`); this.name = "DockerCliTransportCanceled"; } }
export type DockerCliRunner = Readonly<{ run(argv: readonly string[], signal: AbortSignal): Promise<DockerProcessExit> }>;
export type DockerCliImageTransportOptions = Readonly<{ runner: DockerCliRunner; owner: string; hostPort: number; containerPort: number; allowedNetworks: readonly string[]; networkName?: string }>;
const names = (candidate: DockerImageCandidateV1) => { const suffix = candidate.candidateId.slice(`${candidate.deploymentId}:candidate:`.length); return { candidate: `deploylite-candidate-${candidate.deploymentId}-${suffix}`, active: `deploylite-active-${candidate.deploymentId}` }; };
const signal = (input: AbortSignal | undefined) => input ?? new AbortController().signal;

export class DockerCliImageTransport implements DockerImageTransport {
  constructor(private readonly options: DockerCliImageTransportOptions) {}
  async startCandidate(candidate: DockerImageCandidateV1, abort: AbortSignal): Promise<void> { await this.run("start", buildDockerRunArgv({ candidate, projectId: candidate.projectId, containerName: names(candidate).candidate, hostPort: this.options.hostPort, containerPort: this.options.containerPort, owner: this.options.owner, allowedNetworks: this.options.allowedNetworks, networkName: this.options.networkName }), abort); }
  async checkHealth(candidate: DockerImageCandidateV1, abort: AbortSignal): Promise<boolean> { try { const result = await this.options.runner.run(buildDockerInspectArgv(names(candidate).candidate), signal(abort)); return result.exitCode === 0 && result.stdout.trim() === "healthy"; } catch (error) { if (abort.aborted) throw new DockerCliTransportCanceled("health"); return false; } }
  async promoteCandidate(candidate: DockerImageCandidateV1, priorOrSignal: AbortSignal | import("@deploylite/domain").PriorDockerImageExecutionReceiptV1 | undefined, signalOrSource?: AbortSignal | string, suppliedSignal?: AbortSignal): Promise<void> { const abort = suppliedSignal ?? (signalOrSource instanceof AbortSignal ? signalOrSource : priorOrSignal instanceof AbortSignal ? priorOrSignal : undefined); if (!abort) throw new DockerCliTransportFailure("promote"); const resource = names(candidate); await this.verifyOwnership(resource.candidate, candidate.deploymentId, candidate.candidateId, candidate.effectiveImage, abort); await this.run("promote", buildDockerRenameArgv(resource.candidate, resource.active), abort); }
  async restorePrior(receipt: ProvenDockerImageExecutionReceiptV1 & { projectId?: string; runtimeConfig?: { hostPort: number; containerPort: number; networkName?: string } }, abort: AbortSignal): Promise<void> { if (!receipt.candidateId || !receipt.projectId || !receipt.runtimeConfig || receipt.runtimeConfig.hostPort !== this.options.hostPort || receipt.runtimeConfig.containerPort !== this.options.containerPort || receipt.runtimeConfig.networkName !== this.options.networkName) throw new DockerCliTransportFailure("restore"); const candidate = { candidateId: receipt.candidateId, projectId: receipt.projectId, deploymentId: receipt.deploymentId, effectiveImage: receipt.effectiveImage, runtimePort: receipt.runtimeConfig.containerPort, networkName: receipt.runtimeConfig.networkName }; const resource = names(candidate); const inspected = await this.options.runner.run(buildDockerRestoreInspectArgv(resource.active), signal(abort)); if (inspected.exitCode !== 0) throw new DockerCliTransportFailure("restore", inspected); const [owner, project, deployment, candidateId, image, state, health] = inspected.stdout.trim().split("|"); if (owner !== this.options.owner || project !== receipt.projectId || deployment !== receipt.deploymentId || candidateId !== receipt.candidateId || image !== receipt.effectiveImage || (state !== "running" && state !== "exited" && state !== "created")) throw new DockerCliTransportFailure("restore", inspected); if (state === "running") { if (health !== "healthy") throw new DockerCliTransportFailure("restore", inspected); return; } await this.run("restore", buildDockerStartArgv(resource.active), abort); const healthy = await this.options.runner.run(buildDockerInspectArgv(resource.active), signal(abort)); if (healthy.exitCode !== 0 || healthy.stdout.trim() !== "healthy") throw new DockerCliTransportFailure("restore", healthy); }
  async discardCandidate(candidate: DockerImageCandidateV1, abort: AbortSignal): Promise<void> { const resource = names(candidate); await this.verifyOwnership(resource.candidate, candidate.deploymentId, candidate.candidateId, candidate.effectiveImage, abort); await this.run("discard", buildDockerRemoveArgv(resource.candidate), abort); }
  async stopOwned(input: { projectId: string; deploymentId: string; candidateId: string; effectiveImage: string }, abort: AbortSignal): Promise<"stopped" | "already-stopped" | "absent" | "failed" | "canceled"> { try { const result = await this.options.runner.run(buildDockerOwnedStopLookupArgv({ ...input, owner: this.options.owner }), signal(abort)); if (result.exitCode !== 0) throw new DockerCliTransportFailure("lookup", result); const records = result.stdout.trim() ? result.stdout.trim().split("\n").map((line) => line.split("|")) : []; if (records.length === 0) return "absent"; if (records.length !== 1 || !records[0]?.[0]) throw new DockerCliTransportFailure("ownership", result); const [containerId] = records[0]; const inspected = await this.options.runner.run(buildDockerStopOwnershipInspectArgv(containerId!), signal(abort)); const [owner, project, deployment, candidate, image, state] = inspected.stdout.trim().split("|"); if (inspected.exitCode !== 0 || owner !== this.options.owner || project !== input.projectId || deployment !== input.deploymentId || candidate !== input.candidateId || image !== input.effectiveImage) throw new DockerCliTransportFailure("ownership", inspected); if (state !== "running") return "already-stopped"; await this.run("stop", buildDockerStopArgv(containerId!), abort); return "stopped"; } catch (error) { return abort.aborted ? "canceled" : "failed"; } }
  private async verifyOwnership(name: string, deploymentId: string, candidateId: string, effectiveImage: string, abort: AbortSignal, allowMissing = false): Promise<void> { try { const result = await this.options.runner.run(buildDockerOwnershipInspectArgv(name), signal(abort)); if (result.exitCode !== 0) { if (allowMissing && /no such object/i.test(result.stderr)) return; throw new DockerCliTransportFailure("ownership", result); } const [owner, deployment, candidate, image] = result.stdout.trim().split("|"); if (owner !== this.options.owner || deployment !== deploymentId || candidate !== candidateId || image !== effectiveImage) throw new DockerCliTransportFailure("ownership", result); } catch (error) { if (abort.aborted) throw new DockerCliTransportCanceled("ownership"); if (error instanceof DockerCliTransportFailure) throw error; throw new DockerCliTransportFailure("ownership"); } }
  private async run(operation: string, argv: readonly string[], abort: AbortSignal): Promise<void> { try { const result = await this.options.runner.run(argv, signal(abort)); if (result.exitCode !== 0) throw new DockerCliTransportFailure(operation, result); } catch (error) { if (abort.aborted) throw new DockerCliTransportCanceled(operation); if (error instanceof DockerCliTransportFailure) throw error; throw new DockerCliTransportFailure(operation); } }
}
