import { describe, expect, it } from "vitest";
import { createDeploymentSnapshot, createSourceIntent, type DeploymentSnapshotV1, type ImageReferencePolicyV1 } from "@deploylite/contracts";
import { DockerImageExecutor } from "./docker-image-executor.js";
import { FakeDockerImageTransport } from "./testing/fake-docker-image-transport.js";
import { InMemoryProtocolTransport } from "./protocol-memory.js";
const policy: ImageReferencePolicyV1 = { policyVersion: "policy-1", trustedHosts: ["registry.example.com"], allowTags: true, allowDigests: true };
const digest = `sha256:${"a".repeat(64)}`;
const snapshot = (port: number | null = 3000, reference = `registry.example.com/team/app@${digest}`, resolvedDigest?: string): DeploymentSnapshotV1 => createDeploymentSnapshot({ deploymentId: "dep-1", projectId: "project-1", source: createSourceIntent({ sourceMode: "image", requestedReference: reference }, policy), configRevision: "config-1", runtimeRevision: "runtime-1", runtimePort: port, secretRefs: [], policyVersion: policy.policyVersion, schemaVersion: 1, resolvedDigest }, { sha256: () => "b".repeat(64) });
const protocol = () => new InMemoryProtocolTransport({ clock: { now: () => 1000 }, leasePolicy: { ttlMs: 1000 }, retryPolicy: { maxAttempts: 1, deadlineMs: 0, backoffMs: () => 0 }, capabilities: ["deploy.execute"] });
const run = async (input: Partial<Parameters<DockerImageExecutor["execute"]>[0]> = {}, transport = new FakeDockerImageTransport()) => { const p = protocol(); const s = input.snapshot ?? snapshot(); const e = new DockerImageExecutor({ protocol: p, transport, trustedHosts: policy.trustedHosts, allowedNetworks: ["deploylite"] }); return { p, transport, result: await e.execute({ snapshot: s, commandId: "command-1", lease: p.claimLease(s.deploymentId), ...input }) }; };
describe("DockerImageExecutor", () => {
  it("runs a digest-pinned candidate and ACKs ordered success", async () => { const { p, transport, result } = await run(); expect(transport.calls).toEqual(["start", "health", "promote"]); expect(result).toMatchObject({ effectiveImage: `registry.example.com/team/app@${digest}`, runtimePort: 3000, terminalStatus: "succeeded", proven: true }); expect(p.getAck("dep-1")?.kind).toBe("terminal-ack"); });
  it("supports a bounded optional network and rolls back an unhealthy candidate", async () => { const prior = { deploymentId: "dep-1", effectiveImage: `registry.example.com/team/old@${digest}`, runtimePort: 3000, health: "passed" as const, terminalStatus: "succeeded" as const, rollback: { target: null, result: "not-required" as const }, proven: true as const }; const { transport, result } = await run({ networkName: "deploylite", priorProvenReceipt: prior }, new FakeDockerImageTransport({ health: [false] })); expect(transport.calls).toEqual(["start", "health", "restore", "discard"]); expect(result.rollback).toEqual({ target: prior.effectiveImage, result: "restored" }); });
  it("rejects an unresolved tag, invalid port, and disallowed network before transport", async () => { for (const input of [{ snapshot: snapshot(3000, "registry.example.com/team/app:stable") }, { snapshot: snapshot(65536) }, { snapshot: snapshot(), networkName: "outside" }] as const) { const transport = new FakeDockerImageTransport(); await expect(run(input, transport)).rejects.toThrow(); expect(transport.calls).toEqual([]); } });
  it("checks capability, lease, and replay before effects", async () => { const transport = new FakeDockerImageTransport(); const p = new InMemoryProtocolTransport({ clock: { now: () => 1000 }, leasePolicy: { ttlMs: 1000 }, retryPolicy: { maxAttempts: 1, deadlineMs: 0, backoffMs: () => 0 }, capabilities: [] }); const e = new DockerImageExecutor({ protocol: p, transport, trustedHosts: policy.trustedHosts }); await expect(e.execute({ snapshot: snapshot(), commandId: "c", lease: p.claimLease("dep-1") })).rejects.toThrow("capability"); expect(transport.calls).toEqual([]); });
  it("has no forbidden effect imports", async () => { const source = await import("node:fs/promises").then(({ readFile }) => readFile(new URL("./docker-image-executor.ts", import.meta.url), "utf8")); expect(source).not.toMatch(/node:(child_process|fs|net|http|https)|from ["'][^"']*(docker|registry|vps|secret)/); });
});
