import { CapabilityError, CapabilityRegistry, Clock, createDeploymentCommand, DeploymentCommandInputV1, DeploymentCommandV1, DeliveryResultV1, FenceError, InMemoryCapabilityRegistry, LeaseExpiredError, LeasePolicy, ProtocolDispatch, ProtocolError, ProtocolValidationError, ReplayConflictError, RetryExhaustedError, RetryPolicy, isRetryableProtocolError, protocolPayloadFingerprint, TransportError } from "@deploylite/contracts";
export interface InMemoryProtocolTransportOptions { readonly clock: Clock; readonly leasePolicy: LeasePolicy; readonly retryPolicy: RetryPolicy; readonly capabilities: CapabilityRegistry | readonly string[]; readonly dispatch?: ProtocolDispatch<unknown>; }
type Replay = { fingerprint: string; result: DeliveryResultV1<unknown> };
const copy = <T>(value: T): T => structuredClone(value);
export class InMemoryProtocolTransport {
  readonly #clock: Clock; readonly #leasePolicy: LeasePolicy; readonly #retryPolicy: RetryPolicy; readonly #capabilities: CapabilityRegistry; readonly #dispatch?: ProtocolDispatch<unknown>; readonly #leases = new Map<string, { leaseId: string; deploymentId: string; fence: number; expiresAt: number }>(); readonly #replays = new Map<string, Replay>();
  constructor(options: InMemoryProtocolTransportOptions) { if (!Number.isInteger(options.retryPolicy.maxAttempts) || options.retryPolicy.maxAttempts < 1 || options.retryPolicy.deadlineMs < 0 || options.leasePolicy.ttlMs <= 0) throw new ProtocolValidationError("invalid retry or lease policy"); this.#clock = options.clock; this.#retryPolicy = options.retryPolicy; this.#leasePolicy = options.leasePolicy; this.#capabilities = Array.isArray(options.capabilities) ? new InMemoryCapabilityRegistry(options.capabilities as readonly string[]) : options.capabilities as CapabilityRegistry; this.#dispatch = options.dispatch; }
  claimLease(deploymentId: string) { const id = deploymentId.trim(); if (!id) throw new ProtocolValidationError("deploymentId must be non-empty"); const fence = (this.#leases.get(id)?.fence ?? 0) + 1; const result = { leaseId: `${id}:lease:${fence}`, deploymentId: id, fence, expiresAt: this.#clock.now() + this.#leasePolicy.ttlMs }; this.#leases.set(id, result); return copy(result); }
  createCommand<T>(input: Omit<DeploymentCommandInputV1<T>, "schemaVersion"> & { schemaVersion?: number }) { return createDeploymentCommand({ ...input, schemaVersion: input.schemaVersion ?? 1 }); }
  deliver<T = unknown>(command: DeploymentCommandV1, dispatch?: ProtocolDispatch<T>): DeliveryResultV1<T> { const normalized = createDeploymentCommand(command); for (const capability of normalized.requiredCapabilities) if (!this.#capabilities.has(capability)) throw new CapabilityError(capability); const fingerprint = protocolPayloadFingerprint(normalized.payload); const prior = this.#replays.get(normalized.commandId); if (prior) { if (prior.fingerprint !== fingerprint || prior.result.deploymentId !== normalized.deploymentId) throw new ReplayConflictError(); return { ...copy(prior.result), replayed: true } as DeliveryResultV1<T>; } this.#validateLease(normalized.lease); const effect = dispatch ?? this.#dispatch as ProtocolDispatch<T> | undefined ?? (() => undefined as T); const started = this.#clock.now(); const backoff: number[] = []; for (let attempt = 1; ; attempt++) { try { const result = effect(normalized, attempt); const delivery = { schemaVersion: 1 as const, commandId: normalized.commandId, deploymentId: normalized.deploymentId, payloadFingerprint: fingerprint, attempts: attempt, backoffMs: backoff, replayed: false, result }; this.#replays.set(normalized.commandId, { fingerprint, result: copy(delivery) }); return copy(delivery); } catch (error) { const failure = error instanceof ProtocolError ? error : new TransportError(error instanceof Error ? error.message : "transport failed"); if (!isRetryableProtocolError(failure)) throw failure; const delay = this.#retryPolicy.backoffMs(attempt); if (!Number.isFinite(delay) || delay < 0) throw new ProtocolValidationError("retry backoff must be non-negative"); if (attempt >= this.#retryPolicy.maxAttempts || this.#clock.now() - started + delay > this.#retryPolicy.deadlineMs) throw new RetryExhaustedError(attempt, failure); backoff.push(delay); this.#validateLease(normalized.lease); } } }
  #validateLease(lease: { leaseId: string; deploymentId: string; fence: number; expiresAt: number }) { const current = this.#leases.get(lease.deploymentId); if (current && (lease.fence < current.fence || (lease.fence === current.fence && current.leaseId !== lease.leaseId))) throw new FenceError(); if (!current || lease.fence > current.fence) this.#leases.set(lease.deploymentId, copy(lease)); if (this.#clock.now() >= lease.expiresAt) throw new LeaseExpiredError(); }
}
