import { AckResultV1, AckStateV1, AckOrderError, CapabilityError, CapabilityRegistry, Clock, createDeploymentCommand, createStageAck, createTerminalAck, createTerminalIntent, DeploymentCommandInputV1, DeploymentCommandV1, DeliveryResultV1, FenceError, InMemoryCapabilityRegistry, LeaseExpiredError, LeasePolicy, ProtocolDispatch, ProtocolError, ProtocolValidationError, ReplayConflictError, RetryExhaustedError, RetryPolicy, isRetryableProtocolError, protocolPayloadFingerprint, StageAckV1, TerminalAckV1, TerminalIntentV1, TransportError } from "@deploylite/contracts";
export interface InMemoryProtocolTransportOptions { readonly clock: Clock; readonly leasePolicy: LeasePolicy; readonly retryPolicy: RetryPolicy; readonly capabilities: CapabilityRegistry | readonly string[]; readonly dispatch?: ProtocolDispatch<unknown>; }
type Replay = { fingerprint: string; result: DeliveryResultV1<unknown> };
const copy = <T>(value: T): T => structuredClone(value);
export class InMemoryProtocolTransport {
  readonly #clock: Clock; readonly #leasePolicy: LeasePolicy; readonly #retryPolicy: RetryPolicy; readonly #capabilities: CapabilityRegistry; readonly #dispatch?: ProtocolDispatch<unknown>; readonly #leases = new Map<string, { leaseId: string; deploymentId: string; fence: number; expiresAt: number }>(); readonly #replays = new Map<string, Replay>(); readonly #acks = new Map<string, AckStateV1>();
  constructor(options: InMemoryProtocolTransportOptions) { if (!Number.isInteger(options.retryPolicy.maxAttempts) || options.retryPolicy.maxAttempts < 1 || options.retryPolicy.deadlineMs < 0 || options.leasePolicy.ttlMs <= 0) throw new ProtocolValidationError("invalid retry or lease policy"); this.#clock = options.clock; this.#retryPolicy = options.retryPolicy; this.#leasePolicy = options.leasePolicy; this.#capabilities = Array.isArray(options.capabilities) ? new InMemoryCapabilityRegistry(options.capabilities as readonly string[]) : options.capabilities as CapabilityRegistry; this.#dispatch = options.dispatch; }
  claimLease(deploymentId: string) { const id = deploymentId.trim(); if (!id) throw new ProtocolValidationError("deploymentId must be non-empty"); const fence = (this.#leases.get(id)?.fence ?? 0) + 1; const result = { leaseId: `${id}:lease:${fence}`, deploymentId: id, fence, expiresAt: this.#clock.now() + this.#leasePolicy.ttlMs }; this.#leases.set(id, result); return copy(result); }
  createCommand<T>(input: Omit<DeploymentCommandInputV1<T>, "schemaVersion"> & { schemaVersion?: number }) { return createDeploymentCommand({ ...input, schemaVersion: input.schemaVersion ?? 1 }); }
  deliver<T = unknown>(command: DeploymentCommandV1, dispatch?: ProtocolDispatch<T>): DeliveryResultV1<T> { const normalized = createDeploymentCommand(command); for (const capability of normalized.requiredCapabilities) if (!this.#capabilities.has(capability)) throw new CapabilityError(capability); const fingerprint = protocolPayloadFingerprint(normalized.payload); const prior = this.#replays.get(normalized.commandId); if (prior) { if (prior.fingerprint !== fingerprint || prior.result.deploymentId !== normalized.deploymentId) throw new ReplayConflictError(); return { ...copy(prior.result), replayed: true } as DeliveryResultV1<T>; } this.#validateLease(normalized.lease); const effect = dispatch ?? this.#dispatch as ProtocolDispatch<T> | undefined ?? (() => undefined as T); const started = this.#clock.now(); const backoff: number[] = []; for (let attempt = 1; ; attempt++) { try { const result = effect(normalized, attempt); const delivery = { schemaVersion: 1 as const, commandId: normalized.commandId, deploymentId: normalized.deploymentId, payloadFingerprint: fingerprint, attempts: attempt, backoffMs: backoff, replayed: false, result }; this.#replays.set(normalized.commandId, { fingerprint, result: copy(delivery) }); return copy(delivery); } catch (error) { const failure = error instanceof ProtocolError ? error : new TransportError(error instanceof Error ? error.message : "transport failed"); if (!isRetryableProtocolError(failure)) throw failure; const delay = this.#retryPolicy.backoffMs(attempt); if (!Number.isFinite(delay) || delay < 0) throw new ProtocolValidationError("retry backoff must be non-negative"); if (attempt >= this.#retryPolicy.maxAttempts || this.#clock.now() - started + delay > this.#retryPolicy.deadlineMs) throw new RetryExhaustedError(attempt, failure); backoff.push(delay); this.#validateLease(normalized.lease); } } }
  #validateLease(lease: { leaseId: string; deploymentId: string; fence: number; expiresAt: number }) { const current = this.#leases.get(lease.deploymentId); if (current && (lease.fence < current.fence || (lease.fence === current.fence && current.leaseId !== lease.leaseId))) throw new FenceError(); if (!current || lease.fence > current.fence) this.#leases.set(lease.deploymentId, copy(lease)); if (this.#clock.now() >= lease.expiresAt) throw new LeaseExpiredError(); }
  recordStageAck(input: StageAckV1): AckResultV1 { const ack = createStageAck(input); this.#validateLease(ack.lease); const current = this.#acks.get(ack.deploymentId); if (!current) { const state = { kind: "stage" as const, ...copy(ack) }; this.#acks.set(ack.deploymentId, state); return { state: copy(state), replayed: false }; } if (current.kind !== "stage") return { state: copy(current), replayed: true }; if (current.sequence === ack.sequence && current.stage === ack.stage && current.commandId === ack.commandId) return { state: copy(current), replayed: true }; if (ack.sequence <= current.sequence) throw new AckOrderError("stage ACK sequence must advance monotonically"); const state = { kind: "stage" as const, ...copy(ack) }; this.#acks.set(ack.deploymentId, state); return { state: copy(state), replayed: false }; }
  recordTerminalIntent(input: TerminalIntentV1): AckResultV1 { const intent = createTerminalIntent(input); this.#validateLease(intent.lease); const current = this.#acks.get(intent.deploymentId); if (current?.kind === "terminal-pending-ack" || current?.kind === "terminal-ack") { if (current.commandId !== intent.commandId || current.status !== intent.status) throw new AckOrderError("terminal intent contradicts durable state"); return { state: copy(current), replayed: true }; } const state = { kind: "terminal-pending-ack" as const, ...copy(intent) }; this.#acks.set(intent.deploymentId, state); return { state: copy(state), replayed: false }; }
  recordTerminalAck(input: TerminalAckV1): AckResultV1 { const ack = createTerminalAck(input); this.#validateLease(ack.lease); const current = this.#acks.get(ack.deploymentId); if (!current || current.kind === "stage") throw new AckOrderError("terminal ACK requires a durable terminal intent"); if (current.commandId !== ack.commandId || current.status !== ack.status) throw new AckOrderError("terminal ACK contradicts durable intent"); if (current.kind === "terminal-ack") return { state: copy(current), replayed: true }; const state = { ...copy(current), kind: "terminal-ack" as const }; this.#acks.set(ack.deploymentId, state); return { state, replayed: false }; }
  getAck(deploymentId: string): AckStateV1 | null { const state = this.#acks.get(deploymentId); return state ? copy(state) : null; }
}
