import { afterEach, describe, expect, it, vi } from "vitest";
import { InMemoryCapabilityRegistry, type ComposeResourceObservationV1, type ComposeResourceKind, type ComposeResourceCleanupInput as Input, type ComposeResourceCleanupPreviewV1 as Preview } from "@deploylite/contracts";
import { prepareComposeResourceCleanup as prepare, validateConfirmedComposeResourceCleanup as confirm, type PreparedComposeResourceCleanup, type ComposeResourceCleanupDependencies, createComposePreview, createConfirmation, createControlCommand, digestComposeResourceObservation, resolveControlCommandInMemory, type ControlCommand, type ControlConfirmation, type ControlGrantRepository } from "./index.js";
import type { ComposeAttachmentPreviewDependencies } from "./compose-resource-inspection.js";
type Prepared={-readonly[K in keyof PreparedComposeResourceCleanup]:PreparedComposeResourceCleanup[K]};
type Dependencies={-readonly[K in keyof ComposeResourceCleanupDependencies]:ComposeResourceCleanupDependencies[K]};
afterEach(()=>vi.restoreAllMocks());
const image="registry.example.com/app@sha256:"+"a".repeat(64);
const document=JSON.stringify({services:{app:{image,volumes:[{type:"volume",source:"data",target:"/private-data"}],environment:{TOKEN:"${APP_TOKEN}"}}},volumes:{data:{}}});
const policy={policyVersion:"cleanup-test",trustedHosts:["registry.example.com"],allowTags:false,allowDigests:true};
function fixture(kind:ComposeResourceKind="volume"){
  const preview=createComposePreview(document,"project-1",policy),resource=(kind==="volume"?preview.volumes:preview.networks)[0]!;
  const observation:ComposeResourceObservationV1={schemaVersion:1,owner:"deploylite",agentId:"agent-1",projectId:"project-1",kind,key:resource.key,runtimeName:resource.runtimeName,physicalIdentity:kind==="volume"?"2026-10-08T00:00:00Z":"b".repeat(64),configDigest:preview.configDigest,stateDigest:"0".repeat(64),observedAt:1000,containers:[{containerId:"c".repeat(64),service:"app",running:false,attached:false,mounts:[]}]};
  const seal=()=>{observation.stateDigest=digestComposeResourceObservation(observation);};seal();let now=1010;
  const inspect=vi.fn(async(_input:unknown,_signal:AbortSignal)=>structuredClone(observation));
  const deps:Dependencies={inspection:{imagePolicy:policy,owner:"deploylite",agentId:"agent-1",inspector:{inspect},clock:{now:()=>now},maxAgeMs:100},capabilities:new InMemoryCapabilityRegistry(["compose.resource.inspect.v1"]),actorId:"actor-1",role:"operator",correlationId:"correlation-1",idempotencyKey:"cleanup-key",grants:{listForActor:vi.fn<ControlGrantRepository["listForActor"]>(async actorId=>[{id:"grant-1",actorId,action:"project.delete",scope:{kind:"project",projectId:"project-1"}}])},deadlineMs:1000,confirmationTtlMs:60000};
  const input:Input={document,projectId:"project-1",kind,key:resource.key,expectedConfigDigest:preview.configDigest,expectedStateDigest:observation.stateDigest};
  const expected:Preview={schemaVersion:1,operation:"compose.resource.cleanup",status:"preview",executionAllowed:false,requiresConfirmation:true,projectId:"project-1",kind,key:resource.key,configDigest:preview.configDigest,stateDigest:observation.stateDigest,confirmationTtlMs:60000};
  const command=createControlCommand({actorId:deps.actorId,action:"project.delete",scope:{kind:"project",projectId:input.projectId},input:{...expected,owner:"deploylite",agentId:"agent-1"},idempotencyKey:deps.idempotencyKey,correlationId:deps.correlationId,expiresAt:new Date(now+60000)});
  const original:Prepared={command,preview:expected,owner:"deploylite",agentId:"agent-1",preparedAtMs:now},confirmation=createConfirmation({command,classification:"destructive"});
  return{input,deps,observation,seal,inspect,expected,original,confirmation,advance:(time:number)=>{now=time;observation.observedAt=time-10;}};
}
describe("effect-free exact owned resource cleanup admission",()=>{
  for(const kind of ["network","volume"] as const)it(`prepares a detached owned ${kind} with an existing pending destructive command`,async()=>{
    const f=fixture(kind),r=await prepare(f.input,f.deps);expect(r).toMatchObject({preview:f.expected,owner:"deploylite",agentId:"agent-1",preparedAtMs:1010,command:{action:"project.delete",scope:{kind:"project",projectId:"project-1"},status:"pending_confirmation",expiresAt:new Date(61010)}});expect(r.command.inputDigest).toBe(f.original.command.inputDigest);
    for(const secret of [document,image,"APP_TOKEN","/private-data","c".repeat(64),f.observation.physicalIdentity])expect(JSON.stringify(r.preview)).not.toContain(secret);
  });
  for(const role of ["read-only","auditor"] as const)it(`denies ${role} before observation`,async()=>{const f=fixture();f.deps.role=role;await expect(prepare(f.input,f.deps)).rejects.toMatchObject({code:"COMPOSE_CLEANUP_FORBIDDEN"});expect(f.inspect).not.toHaveBeenCalled();});
  for(const mode of ["action","scope"] as const)it(`requires the existing destructive ${mode} grant`,async()=>{const f=fixture();f.deps.grants.listForActor=async actorId=>[{id:"bad",actorId,action:mode==="action"?"project.deploy":"project.delete",scope:{kind:"project",projectId:mode==="scope"?"foreign":"project-1"}}];await expect(prepare(f.input,f.deps)).rejects.toMatchObject({code:"COMPOSE_CLEANUP_FORBIDDEN"});expect(f.inspect).not.toHaveBeenCalled();});
  it.each([{execute:true},{purge:true},{owner:"foreign"},{runtimeName:"private"},{confirmationTtlMs:999},{projectId:"bad/path"}])("rejects caller authority and unbounded cleanup overrides %#",async extra=>{const f=fixture();await expect(prepare({...f.input,...extra},f.deps)).rejects.toMatchObject({code:"COMPOSE_CLEANUP_INVALID"});expect(f.inspect).not.toHaveBeenCalled();});
  for(const field of ["expectedConfigDigest","expectedStateDigest"] as const)it(`refuses stale ${field}`,async()=>{const f=fixture();await expect(prepare({...f.input,[field]:"f".repeat(64)},f.deps)).rejects.toMatchObject({code:"COMPOSE_CLEANUP_STALE"});});
  for(const running of [false,true])it(`rejects every attached consumer, running=${running}`,async()=>{const f=fixture();f.observation.containers[0]!.attached=true;f.observation.containers[0]!.running=running;f.seal();await expect(prepare({...f.input,expectedStateDigest:f.observation.stateDigest},f.deps)).rejects.toMatchObject({code:"COMPOSE_CLEANUP_IN_USE"});});
  it("rejects a foreign observation",async()=>{const f=fixture();f.observation.owner="other";f.seal();await expect(prepare({...f.input,expectedStateDigest:f.observation.stateDigest},f.deps)).rejects.toMatchObject({code:"COMPOSE_CLEANUP_FOREIGN"});});
  it("requires explicit inspection capability",async()=>{const f=fixture();f.deps.capabilities=new InMemoryCapabilityRegistry([]);await expect(prepare(f.input,f.deps)).rejects.toMatchObject({code:"COMPOSE_CLEANUP_UNAVAILABLE"});expect(f.inspect).not.toHaveBeenCalled();});
  it.each([{confirmationTtlMs:0},{confirmationTtlMs:900001},{deadlineMs:0},{deadlineMs:60001}])("bounds server policy %#",async extra=>{const f=fixture();await expect(prepare(f.input,{...f.deps,...extra})).rejects.toMatchObject({code:"COMPOSE_CLEANUP_INVALID"});expect(f.inspect).not.toHaveBeenCalled();});
  it("rejects pre-cancelled work before observation",async()=>{const f=fixture(),c=new AbortController();c.abort();await expect(prepare(f.input,f.deps,c.signal)).rejects.toMatchObject({code:"COMPOSE_CLEANUP_FAILED"});expect(f.inspect).not.toHaveBeenCalled();});
  it("bounds an uncooperative observer and forwards cancellation",async()=>{const f=fixture();f.deps.deadlineMs=10;let signal:AbortSignal|undefined;f.deps.inspection={...f.deps.inspection,inspector:{inspect:async(_input,s)=>{signal=s;return new Promise(()=>undefined);}}};await expect(prepare(f.input,f.deps)).rejects.toMatchObject({code:"COMPOSE_CLEANUP_FAILED"});expect(signal?.aborted).toBe(true);});
  it("refuses revoked capability after observation",async()=>{const f=fixture();let enabled=true;f.deps.capabilities={has:()=>enabled};f.deps.inspection={...f.deps.inspection,inspector:{inspect:async()=>{enabled=false;return structuredClone(f.observation);}}};await expect(prepare(f.input,f.deps)).rejects.toMatchObject({code:"COMPOSE_CLEANUP_UNAVAILABLE"});});
  it("reuses the original shared reservation on retry without extending its expiry",async()=>{const f=fixture(),ledger=new Map<string,ControlCommand>();const first=await prepare(f.input,f.deps);expect(first).toHaveProperty("command");const a=resolveControlCommandInMemory(ledger,first.command);f.advance(1020);const again=await prepare(f.input,f.deps);const b=resolveControlCommandInMemory(ledger,again.command);expect(b.created).toBe(false);expect(b.command).toEqual(a.command);expect(ledger.size).toBe(1);});
  it("conflicts through the shared resolver when retry intent changes",async()=>{const f=fixture(),ledger=new Map<string,ControlCommand>();const first=await prepare(f.input,f.deps);expect(first).toHaveProperty("command");resolveControlCommandInMemory(ledger,first.command);f.deps.confirmationTtlMs=50000;const next=await prepare(f.input,f.deps);expect(()=>resolveControlCommandInMemory(ledger,next.command)).toThrowError(expect.objectContaining({code:"IDEMPOTENCY_CONFLICT"}));});
});
describe("fresh exact destructive confirmation validation",()=>{
  it("reobserves the exact original intent without consuming confirmation or changing command status",async()=>{const f=fixture(),before=structuredClone({original:f.original,confirmation:f.confirmation});const r=await confirm(f.input,f.original,f.confirmation,f.deps);expect(r).toEqual({...f.expected,commandId:f.original.command.id,confirmationId:f.confirmation.id,confirmationValidated:true});expect({original:f.original,confirmation:f.confirmation}).toEqual(before);expect(f.inspect).toHaveBeenCalledTimes(1);});
  it.each([{commandId:"foreign"},{actorId:"foreign"},{action:"project.deploy"},{scope:{kind:"project",projectId:"foreign"}},{inputDigest:"f".repeat(64)},{classification:"non-destructive"},{consumedAt:new Date(1000)},{expiresAt:new Date(1010)},{expiresAt:new Date(61011)}])("rejects invalid or replayed confirmation %# before observation",async extra=>{const f=fixture();await expect(confirm(f.input,f.original,{...f.confirmation,...extra} as ControlConfirmation,f.deps)).rejects.toMatchObject({code:"COMPOSE_CLEANUP_CONFIRMATION_REJECTED"});expect(f.inspect).not.toHaveBeenCalled();});
  it.each([{action:"project.deploy"},{status:"completed"},{inputDigest:"f".repeat(64)},{result:{}},{executionAuthority:{}},{expiresAt:new Date(NaN)}])("rejects a malformed or mismatched original command %#",async extra=>{const f=fixture();f.original.command={...f.original.command,...extra} as ControlCommand;await expect(confirm(f.input,f.original,f.confirmation,f.deps)).rejects.toMatchObject({code:"COMPOSE_CLEANUP_INVALID"});expect(f.inspect).not.toHaveBeenCalled();});
  it("rejects an expired original command without refreshing the reservation",async()=>{const f=fixture();f.advance(61011);await expect(confirm(f.input,f.original,f.confirmation,f.deps)).rejects.toMatchObject({code:"COMPOSE_CLEANUP_EXPIRED"});expect(f.inspect).not.toHaveBeenCalled();expect(f.original.command.expiresAt).toEqual(new Date(61010));expect(f.confirmation.consumedAt).toBeNull();});
  it("rejects current physical identity replacement under the original confirmation",async()=>{const f=fixture();f.observation.physicalIdentity="2026-10-08T00:01:00Z";f.seal();await expect(confirm({...f.input,expectedStateDigest:f.observation.stateDigest},f.original,f.confirmation,f.deps)).rejects.toMatchObject({code:"COMPOSE_CLEANUP_STALE"});expect(f.confirmation.consumedAt).toBeNull();});
  it("rejects a newly attached consumer and leaves confirmation unconsumed",async()=>{const f=fixture();f.observation.containers[0]!.attached=true;f.seal();await expect(confirm(f.input,f.original,f.confirmation,f.deps)).rejects.toMatchObject({code:"COMPOSE_CLEANUP_STALE"});expect(f.confirmation.consumedAt).toBeNull();});
  it("rechecks the current destructive grant",async()=>{const f=fixture();f.deps.grants.listForActor=async()=>[];await expect(confirm(f.input,f.original,f.confirmation,f.deps)).rejects.toMatchObject({code:"COMPOSE_CLEANUP_FORBIDDEN"});expect(f.inspect).not.toHaveBeenCalled();});
  it("refuses expiry reached during observation",async()=>{const f=fixture();f.deps.inspection={...f.deps.inspection,inspector:{inspect:async()=>{f.advance(61011);return structuredClone(f.observation);}}};await expect(confirm(f.input,f.original,f.confirmation,f.deps)).rejects.toMatchObject({code:"COMPOSE_CLEANUP_EXPIRED"});expect(f.confirmation.consumedAt).toBeNull();});
  it("captures original reservation and confirmation before injected callbacks",async()=>{const f=fixture();f.deps.inspection={...f.deps.inspection,clock:{now:()=>{f.original.command.actorId="mutated";f.confirmation.commandId="mutated";return 1010;}}};const r=await confirm(f.input,f.original,f.confirmation,f.deps);expect(r).toMatchObject({commandId:expect.not.stringMatching(/^mutated$/),confirmationValidated:true,executionAllowed:false});});
  it.each([new Date(NaN), "2099-01-01T00:00:00Z"])("rejects invalid confirmation expiry records %#",async expiresAt=>{const f=fixture();await expect(confirm(f.input,f.original,{...f.confirmation,expiresAt} as ControlConfirmation,f.deps)).rejects.toMatchObject({code:"COMPOSE_CLEANUP_CONFIRMATION_REJECTED"});expect(f.inspect).not.toHaveBeenCalled();});

});
