import { afterEach, describe, expect, it, vi } from "vitest";
import type { ComposeResourceCleanupExecutionReceiptV1, ComposeResourceCleanupPreviewV1, ComposeResourceCleanupConfirmationViewV1 } from "@deploylite/contracts";
import * as domain from "./index.js";
import { composeResourceCleanupExecutionDigest, createControlCommand, createConfirmation, digestControlInput, InMemoryExecutionState, type AuditEventInput, type ControlCommand, type ControlConfirmation, type PreparedComposeResourceCleanup } from "./index.js";
type Receipt={commandId:string;confirmationId:string;expiresAt:string;status:"pending_confirmation"|"eligible"|"dispatching"|"completed";idempotent:boolean;preview:ComposeResourceCleanupPreviewV1;execution?:ComposeResourceCleanupExecutionReceiptV1};
type Record={command:ControlCommand;confirmation:ControlConfirmation};
type Subject={actorId:string;projectId:string;idempotencyKey:string;confirmationId:string};
type StorePort={available():boolean;save(input:PreparedComposeResourceCleanup,requestId:string,signal?:AbortSignal):Promise<Receipt>;find(subject:Subject,signal?:AbortSignal):Promise<Record>;admit(input:PreparedComposeResourceCleanup,view:ComposeResourceCleanupConfirmationViewV1,requestId:string,signal?:AbortSignal):Promise<Receipt>;claimExecution(input:PreparedComposeResourceCleanup,confirmationId:string,requestId:string,signal?:AbortSignal):Promise<Receipt>;completeExecution(input:PreparedComposeResourceCleanup,confirmationId:string,execution:ComposeResourceCleanupExecutionReceiptV1,requestId:string,signal?:AbortSignal):Promise<Receipt>};
type Options={ledger:InMemoryExecutionState;clock():number;commitAudit(input:AuditEventInput,publish:()=>void):void};
const Store=(domain as unknown as {InMemoryComposeResourceCleanupStore?:new(options:Options)=>StorePort}).InMemoryComposeResourceCleanupStore;
afterEach(()=>vi.restoreAllMocks());
function fixture(){
  expect(Store).toBeTypeOf("function");let now=1010,failAudit=false,cancelAtCommit:AbortController|undefined;
  const ledger=new InMemoryExecutionState(),events:AuditEventInput[]=[];
  const commitAudit=vi.fn((input:AuditEventInput,publish:()=>void)=>{if(failAudit)throw new Error("private-audit");cancelAtCommit?.abort();publish();events.push(structuredClone(input));});
  const store=new Store!({ledger,clock:()=>now,commitAudit});
  const preview:ComposeResourceCleanupPreviewV1={schemaVersion:1,operation:"compose.resource.cleanup",status:"preview",executionAllowed:false,requiresConfirmation:true,projectId:"project-1",kind:"volume",key:"data",configDigest:"a".repeat(64),stateDigest:"b".repeat(64),confirmationTtlMs:60000};
  const command=createControlCommand({actorId:"actor-1",action:"project.delete",scope:{kind:"project",projectId:"project-1"},input:{...preview,owner:"deploylite",agentId:"agent-1"},idempotencyKey:"cleanup-1",correlationId:"correlation-1",expiresAt:new Date(61010)});
  const prepared:PreparedComposeResourceCleanup={command,preview,owner:"deploylite",agentId:"agent-1",preparedAtMs:1010};
  const subject=(r:Receipt):Subject=>({actorId:"actor-1",projectId:"project-1",idempotencyKey:"cleanup-1",confirmationId:r.confirmationId});
  const view=(r:Receipt):ComposeResourceCleanupConfirmationViewV1=>({...preview,commandId:r.commandId,confirmationId:r.confirmationId,confirmationValidated:true});
  const execution=(confirmationId:string):ComposeResourceCleanupExecutionReceiptV1=>({schemaVersion:1,action:"compose.resource.cleanup",agentId:prepared.agentId,commandId:command.id,
    cleanupCommandId:command.id,confirmationId,projectId:preview.projectId,inputDigest:command.inputDigest,cleanupInputDigest:composeResourceCleanupExecutionDigest(prepared,confirmationId),
    correlationId:command.correlationId,kind:preview.kind,key:preview.key,runtimeName:"dl-"+"d".repeat(32)+"-vol-data",configDigest:preview.configDigest,stateDigest:preview.stateDigest,
    status:"completed",physicalIdentity:"2026-10-08T00:00:00Z",terminalStatus:"removed",idempotent:false,redacted:true});
  const confirmations=()=> (ledger as InMemoryExecutionState&{confirmations:Map<string,ControlConfirmation>}).confirmations;
  return{store,ledger,events,prepared,preview,subject,view,execution,confirmations,commitAudit,advance:(v:number)=>{now=v;},auditFails:()=>{failAudit=true;},cancelAtCommit:(c:AbortController)=>{cancelAtCommit=c;}};
}
describe("atomic cleanup command admission and terminal receipt",()=>{
  it("publishes the original shared command, destructive confirmation and safe audit together",async()=>{const f=fixture(),r=await f.store.save(f.prepared,"request-1");expect(r).toEqual({commandId:f.prepared.command.id,confirmationId:expect.any(String),expiresAt:new Date(61010).toISOString(),status:"pending_confirmation",idempotent:false,preview:f.preview});expect(f.ledger.commands.size).toBe(1);expect(f.confirmations().size).toBe(1);expect(f.events).toEqual([expect.objectContaining({actorUserId:"actor-1",action:"compose.resource.cleanup.prepared",targetType:"project",targetId:"project-1",requestId:"request-1",correlationId:"correlation-1"})]);expect(JSON.stringify(r)+JSON.stringify(f.events)).not.toContain("agent-1");});
  it("reuses original IDs and expiry for simultaneous and later reservations",async()=>{const f=fixture(),[a,b]=await Promise.all([f.store.save(f.prepared,"request-1"),f.store.save(f.prepared,"request-2")]);expect(b).toEqual({...a,idempotent:true});f.advance(1020);const again:PreparedComposeResourceCleanup={...structuredClone(f.prepared),preparedAtMs:1020,command:{...structuredClone(f.prepared.command),expiresAt:new Date(61020)}};expect(await f.store.save(again,"request-3")).toEqual({...a,idempotent:true});expect(f.events).toHaveLength(1);expect(f.confirmations().size).toBe(1);});
  it("conflicts with changed cleanup intent through the shared resolver",async()=>{const f=fixture();await f.store.save(f.prepared,"request-1");const next=structuredClone(f.prepared);next.preview.key="other";next.command.inputDigest=digestControlInput({...next.preview,owner:next.owner,agentId:next.agentId});await expect(f.store.save(next,"request-2")).rejects.toMatchObject({code:"IDEMPOTENCY_CONFLICT"});expect(f.events).toHaveLength(1);});
  it("rolls back all reservation metadata when required audit fails",async()=>{const f=fixture();f.auditFails();await expect(f.store.save(f.prepared,"request-1")).rejects.toMatchObject({code:"COMPOSE_CLEANUP_FAILED"});expect(f.ledger.commands.size).toBe(0);expect(f.confirmations().size).toBe(0);expect(f.events).toHaveLength(0);});
  it.each(["before","commit"] as const)("fences %s cancellation without partial reservation",async stage=>{const f=fixture(),c=new AbortController();if(stage==="before")c.abort();else f.cancelAtCommit(c);await expect(f.store.save(f.prepared,"request-1",c.signal)).rejects.toMatchObject({code:"COMPOSE_CLEANUP_FAILED"});expect(f.ledger.commands.size).toBe(0);expect(f.confirmations().size).toBe(0);expect(f.events).toHaveLength(0);});
  it("admits once and atomically consumes only the matching existing confirmation",async()=>{const f=fixture(),a=await f.store.save(f.prepared,"request-1"),record=await f.store.find(f.subject(a)),original={...f.prepared,command:record.command};expect(record.command).toEqual(f.prepared.command);const r=await f.store.admit(original,f.view(a),"request-2");expect(r).toEqual({...a,status:"eligible",idempotent:false});const current=[...f.ledger.commands.values()][0]!;expect(current.status).toBe("eligible");expect(current).not.toHaveProperty("executionAuthority");expect(current).not.toHaveProperty("result");expect(f.confirmations().get(a.confirmationId)?.consumedAt).toEqual(new Date(1010));expect(f.events.map(v=>v.action)).toEqual(["compose.resource.cleanup.prepared","compose.resource.cleanup.admitted"]);expect(r.preview.executionAllowed).toBe(false);});
  it("reconciles concurrent admission and ambiguous reply with original receipt and one audit",async()=>{const f=fixture(),a=await f.store.save(f.prepared,"request-1"),[x,y]=await Promise.all([f.store.admit(f.prepared,f.view(a),"request-2"),f.store.admit(f.prepared,f.view(a),"request-3")]);expect(y).toEqual({...x,idempotent:true});expect(await f.store.admit(f.prepared,f.view(a),"request-4")).toEqual({...x,idempotent:true});expect(f.events).toHaveLength(2);});
  it("claims the existing shared command once and atomically stores a replayable terminal receipt",async()=>{const f=fixture(),pending=await f.store.save(f.prepared,"request-1");await f.store.admit(f.prepared,f.view(pending),"request-2");const first=await f.store.claimExecution(f.prepared,pending.confirmationId,"request-3");expect(first).toEqual({...pending,status:"dispatching",idempotent:false});const replay=await f.store.claimExecution(f.prepared,pending.confirmationId,"request-4");expect(replay).toEqual({...first,idempotent:true});const terminal=f.execution(pending.confirmationId),completed=await f.store.completeExecution(f.prepared,pending.confirmationId,terminal,"request-5");expect(completed).toEqual({...pending,status:"completed",idempotent:false,execution:terminal});expect(await f.store.completeExecution(f.prepared,pending.confirmationId,terminal,"request-6")).toEqual({...completed,idempotent:true});const command=[...f.ledger.commands.values()][0]!;expect(command.status).toBe("completed");expect(command.result).toEqual(terminal);expect(f.events.map(v=>v.action)).toEqual(["compose.resource.cleanup.prepared","compose.resource.cleanup.admitted","compose.resource.cleanup.execution.started","compose.resource.cleanup.completed"]);});
  it("rolls back the shared dispatch claim when its atomic audit fails",async()=>{const f=fixture(),pending=await f.store.save(f.prepared,"request-1");await f.store.admit(f.prepared,f.view(pending),"request-2");f.auditFails();await expect(f.store.claimExecution(f.prepared,pending.confirmationId,"request-3")).rejects.toMatchObject({code:"COMPOSE_CLEANUP_FAILED"});expect([...f.ledger.commands.values()][0]?.status).toBe("eligible");expect(f.events.map(v=>v.action)).toEqual(["compose.resource.cleanup.prepared","compose.resource.cleanup.admitted"]);});
  it("restores pending command and unconsumed confirmation on admission audit failure",async()=>{const f=fixture(),a=await f.store.save(f.prepared,"request-1");f.auditFails();await expect(f.store.admit(f.prepared,f.view(a),"request-2")).rejects.toMatchObject({code:"COMPOSE_CLEANUP_FAILED"});expect([...f.ledger.commands.values()][0]?.status).toBe("pending_confirmation");expect(f.confirmations().get(a.confirmationId)?.consumedAt).toBeNull();expect(f.events).toHaveLength(1);});
  it("fences cancellation at the consumption commit",async()=>{const f=fixture(),a=await f.store.save(f.prepared,"request-1"),c=new AbortController();f.cancelAtCommit(c);await expect(f.store.admit(f.prepared,f.view(a),"request-2",c.signal)).rejects.toMatchObject({code:"COMPOSE_CLEANUP_FAILED"});expect([...f.ledger.commands.values()][0]?.status).toBe("pending_confirmation");expect(f.confirmations().get(a.confirmationId)?.consumedAt).toBeNull();expect(f.events).toHaveLength(1);});
  it.each(["actorId","projectId","idempotencyKey","confirmationId"] as const)("refuses foreign lookup %s",async field=>{const f=fixture(),a=await f.store.save(f.prepared,"request-1");await expect(f.store.find({...f.subject(a),[field]:"foreign"})).rejects.toMatchObject({code:"COMPOSE_CLEANUP_CONFIRMATION_REJECTED"});expect(f.events).toHaveLength(1);});
  it.each(["commandId","confirmationId","stateDigest"] as const)("refuses changed admission binding %s",async field=>{const f=fixture(),a=await f.store.save(f.prepared,"request-1");await expect(f.store.admit(f.prepared,{...f.view(a),[field]:field==="stateDigest"?"f".repeat(64):"foreign"},"request-2")).rejects.toMatchObject({code:"COMPOSE_CLEANUP_CONFIRMATION_REJECTED"});expect(f.confirmations().get(a.confirmationId)?.consumedAt).toBeNull();});
  it.each(["actorId","inputDigest","consumedAt","expiresAt"] as const)("rechecks corrupted shared confirmation %s before commit",async field=>{const f=fixture(),a=await f.store.save(f.prepared,"request-1"),c=f.confirmations().get(a.confirmationId)!;Object.assign(c,{[field]:field==="consumedAt"?new Date(1000):field==="expiresAt"?new Date(NaN):"foreign"});await expect(f.store.admit(f.prepared,f.view(a),"request-2")).rejects.toMatchObject({code:"COMPOSE_CLEANUP_CONFIRMATION_REJECTED"});expect([...f.ledger.commands.values()][0]?.status).toBe("pending_confirmation");expect(f.events).toHaveLength(1);});
  it.each(["save","find","admit"] as const)("rejects expired original %s without renewing it",async method=>{const f=fixture(),a=await f.store.save(f.prepared,"request-1");f.advance(61010);const promise=method==="save"?f.store.save(f.prepared,"request-2"):method==="find"?f.store.find(f.subject(a)):f.store.admit(f.prepared,f.view(a),"request-2");await expect(promise).rejects.toMatchObject({code:"COMPOSE_CLEANUP_EXPIRED"});expect([...f.ledger.commands.values()][0]?.expiresAt).toEqual(new Date(61010));expect(f.events).toHaveLength(1);});
  it("clones command and confirmation returned from trusted lookup",async()=>{const f=fixture(),a=await f.store.save(f.prepared,"request-1"),record=await f.store.find(f.subject(a));record.command.actorId="changed";record.confirmation.commandId="changed";expect(await f.store.find(f.subject(a))).toMatchObject({command:{actorId:"actor-1"},confirmation:{commandId:a.commandId}});expect(a.preview.key).toBe("data");});
  it("rejects an unrelated shared reservation instead of inventing a cleanup confirmation",async()=>{const f=fixture(),other=structuredClone(f.prepared.command);other.status="completed";domain.resolveControlCommandInMemory(f.ledger.commands,other);await expect(f.store.save(f.prepared,"request-1")).rejects.toMatchObject({code:"COMPOSE_CLEANUP_INVALID"});expect(f.confirmations().size).toBe(0);expect(f.events).toHaveLength(0);});
});
