export const DEPLOYMENT_PROTOCOL_SCHEMA_VERSION = 1 as const;
export type ProtocolErrorCode = "validation-error" | "policy-rejected" | "capability-unsupported" | "lease-expired" | "fence-stale" | "payload-conflict" | "ack-order" | "transport-failed" | "transient-transport" | "transient-lease" | "retry-exhausted";
export class ProtocolError extends Error { constructor(message: string, readonly code: ProtocolErrorCode, readonly retryable = false) { super(message); this.name = "ProtocolError"; } }
export class ProtocolValidationError extends ProtocolError { constructor(message: string) { super(message, "validation-error"); this.name = "ProtocolValidationError"; } }
export class PolicyViolationError extends ProtocolError { constructor(message: string) { super(message, "policy-rejected"); this.name = "PolicyViolationError"; } }
export class CapabilityError extends ProtocolError { constructor(capability: string) { super(`Unsupported protocol capability: ${capability}`, "capability-unsupported"); this.name = "CapabilityError"; } }
export class LeaseExpiredError extends ProtocolError { constructor() { super("Protocol lease is expired", "lease-expired"); this.name = "LeaseExpiredError"; } }
export class FenceError extends ProtocolError { constructor(message = "Protocol lease fence is stale") { super(message, "fence-stale"); this.name = "FenceError"; } }
export class ReplayConflictError extends ProtocolError { constructor() { super("Command identity was replayed with a different payload", "payload-conflict"); this.name = "ReplayConflictError"; } }
export class AckOrderError extends ProtocolError { constructor(message: string) { super(message, "ack-order"); this.name = "AckOrderError"; } }
export class TransportError extends ProtocolError { constructor(message: string) { super(message, "transport-failed"); this.name = "TransportError"; } }
export class TransportTimeoutError extends ProtocolError { constructor() { super("agent transport timed out", "transport-failed"); this.name = "TransportTimeoutError"; } }
export class TransportCanceledError extends ProtocolError { constructor() { super("agent transport was canceled", "transport-failed"); this.name = "TransportCanceledError"; } }
export class TransientTransportError extends ProtocolError { constructor(message: string) { super(message, "transient-transport", true); this.name = "TransientTransportError"; } }
export class TransientLeaseError extends ProtocolError { constructor(message: string) { super(message, "transient-lease", true); this.name = "TransientLeaseError"; } }
export class RetryExhaustedError extends ProtocolError { constructor(readonly attempts: number, readonly lastFailure: ProtocolError) { super(`Protocol retry budget exhausted after ${attempts} attempts`, "retry-exhausted"); this.name = "RetryExhaustedError"; } }
export interface Clock { now(): number; } export interface RetryPolicy { readonly maxAttempts: number; readonly deadlineMs: number; backoffMs(attempt: number): number; } export interface LeasePolicy { readonly ttlMs: number; }
export interface CapabilityRegistry { has(capability: string): boolean; } export class InMemoryCapabilityRegistry implements CapabilityRegistry { readonly #capabilities: ReadonlySet<string>; constructor(capabilities: readonly string[]) { this.#capabilities = new Set(capabilities); } has(capability: string) { return this.#capabilities.has(capability); } list() { return [...this.#capabilities].sort(); } }
export interface CommandPolicy { validate(command: DeploymentCommandV1): void; }
export interface LeaseV1 { readonly leaseId: string; readonly deploymentId: string; readonly fence: number; readonly expiresAt: number; }
export interface DeploymentCommandInputV1<T = unknown> { readonly schemaVersion: number; readonly commandId: string; readonly deploymentId: string; readonly requiredCapabilities: readonly string[]; readonly payload: T; readonly lease: LeaseV1; }
export interface DeploymentCommandV1<T = unknown> extends Omit<DeploymentCommandInputV1<T>, "schemaVersion"> { readonly schemaVersion: 1; }
const copy = <T>(value: T): T => structuredClone(value);
function freeze<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { Object.freeze(value); for (const child of Object.values(value as Record<string, unknown>)) freeze(child); } return value; }
function text(value: unknown, label: string): string { if (typeof value !== "string" || !value.trim()) throw new ProtocolValidationError(`${label} must be non-empty`); return value.trim(); }
function canonical(value: unknown): unknown { if (value === undefined) return undefined; if (value === null || typeof value === "string" || typeof value === "boolean") return value; if (typeof value === "number") { if (!Number.isFinite(value)) throw new ProtocolValidationError("protocol payload numbers must be finite"); return value; } if (Array.isArray(value)) return value.map((item) => item === undefined ? null : canonical(item)); if (typeof value === "object") { const result: Record<string, unknown> = {}; for (const key of Object.keys(value as Record<string, unknown>).sort()) { const item = canonical((value as Record<string, unknown>)[key]); if (item !== undefined) result[key] = item; } return result; } throw new ProtocolValidationError("protocol payload must be JSON-compatible"); }
export function protocolPayloadFingerprint(payload: unknown): string { const value = canonical(payload); if (value === undefined) throw new ProtocolValidationError("protocol payload is required"); return JSON.stringify(value); }
function lease(value: LeaseV1): LeaseV1 { if (!value || typeof value !== "object") throw new ProtocolValidationError("lease is required"); const result = { leaseId: text(value.leaseId, "leaseId"), deploymentId: text(value.deploymentId, "lease deploymentId"), fence: value.fence, expiresAt: value.expiresAt }; if (!Number.isInteger(result.fence) || result.fence < 1 || !Number.isFinite(result.expiresAt)) throw new ProtocolValidationError("lease values are invalid"); return result; }
export function createDeploymentCommand<T>(input: DeploymentCommandInputV1<T>): DeploymentCommandV1<T> { if (!input || input.schemaVersion !== 1 || !Array.isArray(input.requiredCapabilities)) throw new ProtocolValidationError("invalid command envelope"); const command = { schemaVersion: 1 as const, commandId: text(input.commandId, "commandId"), deploymentId: text(input.deploymentId, "deploymentId"), requiredCapabilities: [...new Set(input.requiredCapabilities.map((capability) => text(capability, "capability")))].sort(), payload: copy(canonical(input.payload)) as T, lease: lease(input.lease) }; if (command.lease.deploymentId !== command.deploymentId) throw new ProtocolValidationError("lease deploymentId does not match command"); protocolPayloadFingerprint(command.payload); return freeze(command); }
export function validateDeploymentCommand(command: DeploymentCommandV1): DeploymentCommandV1 { return createDeploymentCommand(command); }
export type ProtocolDispatch<T = unknown> = (command: DeploymentCommandV1, attempt: number) => T;
export interface DeliveryResultV1<T = unknown> { readonly schemaVersion: 1; readonly commandId: string; readonly deploymentId: string; readonly payloadFingerprint: string; readonly attempts: number; readonly backoffMs: readonly number[]; readonly replayed: boolean; readonly result: T; }
export function isRetryableProtocolError(error: unknown): error is ProtocolError { return error instanceof ProtocolError && error.retryable && (error.code === "transient-transport" || error.code === "transient-lease"); }
export interface StageAckInputV1 { readonly schemaVersion: number; readonly deploymentId: string; readonly commandId: string; readonly lease: LeaseV1; readonly stage: string; readonly sequence: number; }
export type StageAckV1 = Omit<StageAckInputV1, "schemaVersion"> & { readonly schemaVersion: 1 };
export const TERMINAL_STATUSES = ["succeeded", "failed", "canceled"] as const;
export type TerminalStatusV1 = (typeof TERMINAL_STATUSES)[number];
export interface TerminalIntentInputV1 { readonly schemaVersion: number; readonly deploymentId: string; readonly commandId: string; readonly lease: LeaseV1; readonly status: TerminalStatusV1; }
export type TerminalIntentV1 = Omit<TerminalIntentInputV1, "schemaVersion"> & { readonly schemaVersion: 1 };
export type TerminalAckV1 = TerminalIntentV1;
function version(value: number) { if (value !== 1) throw new ProtocolValidationError("unsupported protocol schema version"); }
export function createStageAck(input: StageAckInputV1): StageAckV1 { version(input.schemaVersion); if (!Number.isInteger(input.sequence) || input.sequence < 0 || !input.stage.trim()) throw new ProtocolValidationError("invalid stage ACK"); if (input.lease.deploymentId !== input.deploymentId) throw new ProtocolValidationError("lease deploymentId does not match ACK"); return freeze({ ...input, schemaVersion: 1 as const }); }
export function createTerminalIntent(input: TerminalIntentInputV1): TerminalIntentV1 { version(input.schemaVersion); if (!TERMINAL_STATUSES.includes(input.status) || input.lease.deploymentId !== input.deploymentId) throw new ProtocolValidationError("invalid terminal intent"); return freeze({ ...input, schemaVersion: 1 as const }); }
export const createTerminalAck = createTerminalIntent;
export interface StageAckStateV1 extends StageAckV1 { readonly kind: "stage"; }
export interface TerminalPendingAckStateV1 extends Omit<TerminalIntentV1, "schemaVersion"> { readonly kind: "terminal-pending-ack"; }
export interface TerminalAckStateV1 extends Omit<TerminalIntentV1, "schemaVersion"> { readonly kind: "terminal-ack"; }
export type AckStateV1 = StageAckStateV1 | TerminalPendingAckStateV1 | TerminalAckStateV1;
export interface AckResultV1 { readonly state: AckStateV1; readonly replayed: boolean; }
