import { signAgentTransport, validateAgentTransportKey } from "@deploylite/config";
import { agentCapabilityHandshakeSchema, agentExecutionReceiptSchema, deploymentStopAgentReceiptSchema, dockerImageExecutionReceiptSchema, type AgentExecutionCommand, type DeploymentSnapshotV1, type LeaseV1, TransportCanceledError, TransportError, TransportTimeoutError } from "@deploylite/contracts";
import { type DockerImageExecutionReceiptV1 } from "@deploylite/domain";

export type AgentTransportOptions = Readonly<{ endpoint: string; trustKey: string; agentId: string; allowInsecureInternal?: boolean; fetch?: typeof globalThis.fetch; timeoutMs?: number; now?: () => number }>;
export type AgentDispatchContext = Readonly<{ requestId: string; correlationId: string; agentId: string; signal?: AbortSignal; executionDeploymentId?: string }>;
export type DeploymentDispatchReceipt = DockerImageExecutionReceiptV1 & Readonly<{ projectId: string; sourceDeploymentId: string; snapshotHash: string; correlationId: string }>;
export type AgentStopDispatchInput = Readonly<{ projectId: string; deploymentId: string; candidateId: string; effectiveImage: string; commandId: string }>;

export class AuthenticatedAgentDeploymentTransport {
  readonly #options: AgentTransportOptions; readonly #fetch: typeof globalThis.fetch;
  constructor(options: AgentTransportOptions) { this.#options = options; this.#fetch = options.fetch ?? globalThis.fetch; }
  available(): boolean { let url: URL; try { url = new URL(this.#options.endpoint); validateAgentTransportKey(this.#options.trustKey); } catch { return false; } const internal = url.hostname === "localhost" || url.hostname === "agent" || /^(127\.|10\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.)/.test(url.hostname); if (url.username || url.password || url.hash || !["https:", ...(this.#options.allowInsecureInternal && internal ? ["http:"] : [])].includes(url.protocol)) return false; return Boolean(this.#options.agentId.trim()); }
  async dispatch(snapshot: DeploymentSnapshotV1, commandId: string, context?: AgentDispatchContext): Promise<DockerImageExecutionReceiptV1 | DeploymentDispatchReceipt> {
    if (!this.available()) throw new TransportError("agent transport is not configured");
    if (context?.agentId && context.agentId !== this.#options.agentId) throw new TransportError("agent transport identity mismatch");
    const now = this.#options.now ?? Date.now; const timeoutMs = this.#options.timeoutMs ?? 30_000;
    if (context?.signal?.aborted) throw new TransportCanceledError();
      const lease: LeaseV1 = { leaseId: `${snapshot.deploymentId}:transport:1`, deploymentId: snapshot.deploymentId, fence: 1, expiresAt: now() + timeoutMs };
    const executionDeploymentId = context?.executionDeploymentId ?? snapshot.deploymentId; const v2 = context?.executionDeploymentId !== undefined;
    if (v2) { const handshakeRequestSignature = signAgentTransport("GET /capabilities", this.#options.trustKey); const handshakeResponse = await this.#fetch(`${this.#options.endpoint.replace(/\/$/, "")}/capabilities`, { headers: { "x-deploylite-signature": handshakeRequestSignature } }); const responseBinding = handshakeResponse.headers.get("x-deploylite-request-signature"); // This echo binds the response to the signed request target; it does not authenticate the response body.
      if (!handshakeResponse.ok || responseBinding !== handshakeRequestSignature) throw new TransportError("capability_unavailable"); const handshake = agentCapabilityHandshakeSchema.parse(await handshakeResponse.json()); if (handshake.agentId !== this.#options.agentId || !handshake.capabilities.includes("deploy.execute") || !handshake.protocolVersions.includes(2)) throw new TransportError("capability_unavailable"); }
    const body: AgentExecutionCommand = v2 ? { schemaVersion: 2, agentId: context?.agentId ?? this.#options.agentId, commandId, deploymentId: executionDeploymentId, sourceDeploymentId: snapshot.deploymentId, projectId: snapshot.projectId, snapshot: { ...snapshot, canonicalBytes: undefined } as unknown as Record<string, unknown>, snapshotHash: snapshot.hash, requiredCapabilities: ["deploy.execute"], lease: { ...lease, deploymentId: executionDeploymentId }, context: { requestId: context?.requestId ?? commandId, correlationId: context?.correlationId ?? commandId }, timeoutMs, cancellationRequested: false } : { schemaVersion: 1, agentId: context?.agentId ?? this.#options.agentId, commandId, deploymentId: executionDeploymentId, projectId: snapshot.projectId, snapshot: { ...snapshot, canonicalBytes: undefined } as unknown as Record<string, unknown>, snapshotHash: snapshot.hash, requiredCapabilities: ["deploy.execute"], lease, context: { requestId: context?.requestId ?? commandId, correlationId: context?.correlationId ?? commandId }, timeoutMs, cancellationRequested: false };
    const payload = JSON.stringify(body); const controller = new AbortController(); let timedOut = false; let deadlineTimer: ReturnType<typeof setTimeout> | undefined; const abort = () => controller.abort(); const timer = setTimeout(() => { timedOut = true; controller.abort(); }, timeoutMs); context?.signal?.addEventListener("abort", abort, { once: true }); let canceled = false; const cancel = () => { canceled = true; controller.abort(); }; let rejectCanceled: ((error: TransportCanceledError) => void) | undefined; const onCancel = () => { cancel(); rejectCanceled?.(new TransportCanceledError()); }; const cancelPromise = new Promise<never>((_, reject) => { rejectCanceled = reject; if (context?.signal?.aborted) onCancel(); else context?.signal?.addEventListener("abort", onCancel, { once: true }); });
    try {
      const request = this.#fetch(`${this.#options.endpoint.replace(/\/$/, "")}/deployments/execute`, { method: "POST", headers: { "content-type": "application/json", "x-deploylite-signature": signAgentTransport(payload, this.#options.trustKey) }, body: payload, signal: controller.signal });
      const deadline = new Promise<never>((_, reject) => { deadlineTimer = setTimeout(() => { timedOut = true; controller.abort(); reject(new TransportTimeoutError()); }, timeoutMs); });
      const response = await Promise.race([request, deadline, cancelPromise]);
      if (!response.ok) throw new TransportError(`agent transport returned HTTP ${response.status}`);
      const result = agentExecutionReceiptSchema.parse(await response.json());
      if (result.commandId !== commandId || result.deploymentId !== executionDeploymentId || result.receipt.deploymentId !== executionDeploymentId) throw new TransportError("agent receipt identity mismatch");
      const receipt = dockerImageExecutionReceiptSchema.parse(result.receipt) as DockerImageExecutionReceiptV1; if (v2) { if (result.schemaVersion !== 2 || result.sourceDeploymentId !== snapshot.deploymentId || result.snapshotHash !== snapshot.hash || result.correlationId !== (context?.correlationId ?? commandId)) throw new TransportError("agent receipt identity mismatch"); return { ...receipt, projectId: snapshot.projectId, sourceDeploymentId: snapshot.deploymentId, snapshotHash: snapshot.hash, correlationId: result.correlationId }; } if (result.schemaVersion !== 1) throw new TransportError("agent receipt identity mismatch"); return receipt;
    } catch (error) { if (error instanceof TransportError || error instanceof TransportTimeoutError || error instanceof TransportCanceledError) throw error; if (canceled || context?.signal?.aborted) throw new TransportCanceledError(); if (timedOut) throw new TransportTimeoutError(); throw new TransportError(error instanceof Error ? error.message : "agent transport failed"); } finally { clearTimeout(timer); if (deadlineTimer) clearTimeout(deadlineTimer); context?.signal?.removeEventListener("abort", abort); context?.signal?.removeEventListener("abort", onCancel); }
  }
  async dispatchStop(input: AgentStopDispatchInput, context: AgentDispatchContext): Promise<ReturnType<typeof deploymentStopAgentReceiptSchema.parse>> {
    if (!this.available()) throw new TransportError("agent transport is not configured"); if (context.agentId !== this.#options.agentId) throw new TransportError("agent transport identity mismatch"); if (context.signal?.aborted) throw new TransportCanceledError();
    const now = this.#options.now ?? Date.now; const timeoutMs = this.#options.timeoutMs ?? 30_000; const body = { schemaVersion: 1 as const, action: "deployment.stop" as const, agentId: this.#options.agentId, commandId: input.commandId, projectId: input.projectId, deploymentId: input.deploymentId, candidateId: input.candidateId, effectiveImage: input.effectiveImage, requiredCapabilities: ["deployment.stop" as const], lease: { leaseId: `${input.deploymentId}:transport:stop:1`, deploymentId: input.deploymentId, fence: 1, expiresAt: now() + timeoutMs }, context: { requestId: context.requestId, correlationId: context.correlationId }, timeoutMs, cancellationRequested: false };
    const payload = JSON.stringify(body); const controller = new AbortController(); let timedOut = false; let canceled = false; let rejectControl: ((error: Error) => void) | undefined; const abort = () => { canceled = true; controller.abort(); rejectControl?.(new TransportCanceledError()); }; context.signal?.addEventListener("abort", abort, { once: true }); const control = new Promise<never>((_, reject) => { rejectControl = reject; }); const timer = setTimeout(() => { timedOut = true; controller.abort(); rejectControl?.(new TransportTimeoutError()); }, timeoutMs);
    try { const request = this.#fetch(`${this.#options.endpoint.replace(/\/$/, "")}/deployments/stop`, { method: "POST", headers: { "content-type": "application/json", "x-deploylite-signature": signAgentTransport(payload, this.#options.trustKey) }, body: payload, signal: controller.signal }); const response = await Promise.race([request, control]); if (!response.ok) throw new TransportError(`agent transport returned HTTP ${response.status}`); const result = deploymentStopAgentReceiptSchema.parse(await response.json()); if (result.commandId !== input.commandId || result.agentId !== this.#options.agentId || result.projectId !== input.projectId || result.deploymentId !== input.deploymentId || result.correlationId !== context.correlationId) throw new TransportError("agent stop receipt identity mismatch"); return result; } catch (error) { if (error instanceof TransportError || error instanceof TransportTimeoutError || error instanceof TransportCanceledError) throw error; if (canceled || context.signal?.aborted) throw new TransportCanceledError(); if (timedOut) throw new TransportTimeoutError(); throw new TransportError("agent stop transport failed"); } finally { clearTimeout(timer); context.signal?.removeEventListener("abort", abort); }
  }
}
